Cluster should depend on Mariadb
On the first run of the mariadb install I see this error which is resolved on
the second run:
Error: /Stage[main]/Mariadb::Cluster::Status/Database_user[clusterstatus@localhost]: Could not evaluate: Command mysql is missing
Error: Could not prefetch database_grant provider 'mysql': Command mysql is missing

This is fixed on subsequent runs, unless a password problem appears which
prevents mysql from being configured - effectively locking up the puppet run.

See also discussion starting at
https://researchcloud.slack.com/archives/C07JA7FRS/p1581899935050900

Change-Id: Ia9143d4d580c8b6e9ce0b1a0c701d158e2910f8c